### ISSUE TITLE
Merge with ha-google-home

### ISSUE THREAD

**Issue by leikoilja** [Drakulix/googlehome#23]
Hey, @Drakulix, we just found out that you are developing very similar packages as we do at https://github.com/leikoilja/ha-google-home with a few more super talented developers.

Do you want to join and merge our repos together?
We would be much more efficient altogether with the more consistent flow of develop-test-review-release under the same project instead of various smaller similar projects.

Under the hood, we are using python [glocaltokens](https://github.com/leikoilja/glocaltokens) package which main goal is to fetch and provide local authentication tokens that are needed to make API requests to google devices. Keeping it close to `glocaltokens` package will allow for both projects to grow faster with more contributors 💥 

Let us know what you think

**Comment by Drakulix** [comment]
Hey, funny thing, I just found your integration yesterday and was thinking about deprecating mine in favor of your approach.

Some of the differences between our components:

- Clean wrapping of the authentication scheme in the `glocaltokens` package.
I am using the same approach for authentication based on rithvikvibhu script, but hacked into the component. (You can even find some of my older workarounds in that monster-issue regarding the local api: https://github.com/rithvikvibhu/GHLocalApi/issues/39#issuecomment-515469775 ).
- But I revived the old [googledevices](https://github.com/ludeeus/googledevices) package to support providing a local authentication token. (The package was used in the previously deprecated official googlehome component.) It seems you are doing [api requests](https://github.com/leikoilja/ha-google-home/blob/master/custom_components/google_home/api.py) directly.
- I have a semi-working outdated bluetooth scanner (based on the old integration)
- You have more traction, developers and the cleaner codebase

I am lacking the time, but wanted to upstream my work eventually and I think reviving the `googledevices` package is key to that goal, because the home assistant docs state, that [*All API specific code has to be part of a third party library hosted on PyPi*](https://developers.home-assistant.io/docs/creating_platform_code_review#5-communication-with-devicesservices).

What are your goals with the project? Would you be willing to adjust the api layer?
I am happy to help, but I am currently busy with other projects and I am not sure, if I can contribute much else.
The scanner needs [a lot of rework](https://github.com/Drakulix/googlehome/issues/12) to have a chance at upstreaming.
I am happy to mentor anyone giving that a chance and of course you can take any inspiration you want from the repo (its Apache-licensed anyway).

**Comment by leikoilja** [comment]
Sounds good, thanks for getting back to me 💥 

Well, the ultimate goal is to put community efforts together to finally make usable sense of google-assistant enhanced home devices. Our places are packed with google home devices and we run home assistant in parallel but the two sadly doesn't work together for the past 2 years 😅  
With some hard work of few members we have already got something useful out there that is more-less reliably providing alarms/timers information from google devices to HA - which is amazing and i'm personally super happy about!

Speaking technicalities, as long as there is community need and interest to invest effort into the project - we are up for the challenge (I'm talking for myself)! 💥   As you have mentioned, there are a lot more work to be done: API extraction to a separate package (as `googledevices` does), BT triangulation and much more potential of using the rest of available API endpoints. 

You seem knowledgable in the area and skilled in the field - that's why we'd be happy if you'd join our small team :) Ofc, we are all volunteers and can invest only so much time and effort into the project, but it'll definitely be so much more effective to join "forces" :)

As you have mentioned, one way of doing so - you could deprecate the repo in favour of `ha-google-home`, I'll make you `ha-google-home` repo contributor and we take it from there altogether ;)

**Comment by Drakulix** [comment]
Done.

Feel free to send me an invite any time.
