### ISSUE TITLE
Adb installation

### ISSUE THREAD

**Issue by ShaharLahav** [Drakulix/googlehome#3]
When the custom component is being loaded it immediately shuts with an error of "Please install adb", I am running Hassos on rpi3 using docker so it is not that easy to install adb, please help :)

**Comment by Drakulix** [comment]
Well, I do not have a similar platform nor is that really an issue with my component, so I am a bit lost here.

Since hassos is based on raspbian, you should be able to install adb using something similar to: `sudo apt-get install -y android-tools-adb`.

You may then start an adb-server: `sudo adb start-server`
and configure the extension with an `adb_host` and `adb_port` instead (your network ip and likely 5037), so that your home-assistant container might connect to the external running adb.

Alternatively you may try to find a similar image to what I am using for this job: [sorccu/adb](https://hub.docker.com/r/sorccu/adb).

Unfortunately there is no arm build of it, so you either need to find another one or adjust the Dockerfile yourself. You can then link that container to your home-assistant container and access adb that way.

I hope this help to get you started.

**Comment by ShaharLahav** [comment]
You cant use apt-get on hassos :( ill try to link the container.. not a docker expert though.. Thanks!
